baseURL = ""
languageCode = "en-US"
DefaultContentLanguage = "en"
title = "NU Libraries Publishing Template"
paginate = 10
theme = "hulga"
googleAnalytics = ""

[params]
  # show in HTML meta tag
  author = "Northwestern University Libraries"
  abbrev = "NULIB"
  twitter_username = "nulib"
  keywords = "Libraries, Digital Publishing, Scholarly journal"
  description = "A template for publishing scholarly journals using Hugo and GitHub Pages"
  publisher = "Northwestern University Libraries"

  # change bulma's primary color
  primaryColor = "#5555"

  # subtitle on homepage
  subtitle = "A publication by NULIB"

  # copyright text on footer
  copyright = "No rights reserved"

  # license for all articles
  license = "CC-0"

  # license legal code for all articles
  license_uri = ""

  # enable katex rendering on every post page
  math = false

  # enable postcss, mainly for css purge (129kB->20kB->4.8kB gzipped, but this makes build slower)
  postcss = false

  # enable toc on every post page
  toc = true

  # enable TOC auto collapse
  autoCollapseToc = true

  # enable prefers-color-scheme:dark
  darkMedia = false

  # enable hero section's is-bold effect
  heroBold = true

  # enable PWA, prepare your icons and DON'T forget to modify manifest.json
  pwa = true

  # disable jsdelivr cdn, default false
  noCDN = false

  # international standard serial number (issn) for the journal
  issn = "0000-0000"

  # relative path to the favicon image file, name the file favicon.png and put it in the static/img folder
  favicon = "/img/favicon.ico"

  # Wordmark image file, name the file wordmark.png and put it in the static/img folder
  wordmark = "/img/wordmark-invert.png"

  # Lockup image file, name the file lockup.png and put it in the static/img folder
  lockup = "/img/lockup-invert.png"


# to enable different hightlight themes in light/dark mode 
[markup]
  [markup.highlight]
    noClasses = false

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "browse"
    name = "Browse"
    url = "/issues"
    weight = 2
  [[menu.main]]
    identifier = "authors"
    name = "Guidelines"
    url = "/guidelines/"
    weight = 3
  [[menu.main]]
    identifier = "styleguide"
    name = "Style Guide"
    url = "/style-guide/"
    weight = 4
  [[menu.main]]
    identifier = "submit"
    name = "Submit"
    url = "/submit/"
    weight = 5

[taxonomies]
category = "categories"
tag = "tags"
